version: '2.2'

services:
  tinyweb:
    build: ./build/app
    volumes:
      - ./:/var/www/html
    ports:
      - 8085:80
    container_name: tiny
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G
    networks:
      - dock_default
  tinydb:
    build: ./build/db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3308:3306
    container_name: tinydb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      #MYSQL_USER: "myuser"
      #MYSQL_PASSWORD: "mypass"
    deploy:
      resources:
        limits:
          cpus: '4' 
          memory: 6G  
    networks:
      - dock_default
volumes:
  mysql:

networks:
  dock_default:
